apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sleep-07

spec: 
  containers:
    - name: sleep
      image: kiamol/ch03-sleep
      volumeMounts: 
        - name: data
          mountPath: /data-rw

    - name: file-reader
      image: kiamol/ch03-sleep
      volumeMounts:
        - name: data
          mountPath: /data-ro
          readOnly: true

  volumes:
    - name: data
      emptyDir: {}
