apiVersion: v1
kind: Service

metadata:
  name: simple-server-service
  labels:
    app: server
    type: simple
    lang: node

spec:  
  type: NodePort

  selector:
    app: server
    type: simple
    lang: node
  
  ports:
    - port: 8000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-server-deploy
  labels:
    app: server
    type: simple 
    lang: node

spec: 
  replicas: 1

  selector: 
    matchLabels:
      app: server
      type: simple 
      lang: node

  template:
    metadata:
      labels:
        app: server
        type: simple 
        lang: node
    spec:
      containers:
        - name: simple-server
          image: simpleserver:test
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000