apiVersion: v1
kind: Secret

metadata:
  name: token-secret

type: Opaque

stringData:
  token: '64DiHAWnwRKDr26tAUukbSSbqPFIhX5wCxAm3d6t'


# kubectl create secret generic gitea-runner-secret --from-literal=token='64DiHAWnwRKDr26tAUukbSSbqPFIhX5wCxAm3d6t'