apiVersion: apps/v1
kind: Deployment

metadata:
  name: chapter4-deploy

spec:
  selector:
    matchLabels:
      app: chapter4-pod
  template:
    metadata:
      labels:
        app: chapter4-pod

    spec:
      containers:
        - name: chapter4-container
          image: container-image

          env:			            # 환경변수 정의
            - name: env1-name	  # 새로운 환경 변수의 이름 정의
              value: env1-value	# 새로운 환경 변수의 값 정의

            - name: env2-name
              valueFrom:
                configMapKeyRef:                # 설정된 컨피그맵에서 조회  (kubectl create configmap configmap-name --from-literal=path='value')
                  name: [configmap-name]        # 설정된 컨피그맵의 이름
                  value: [value path in file]   # 설정된 컨피그맵에서 읽어 들일 항목

            - name: env3-name
              valueFrom:
                secretKeyRef:           # 설정된 비밀값에서 조회
                  name: [secret-name]   # 비밀값 이름
                  key: [secret-key]     # 비밀값의 항목 이름


          envFrom:                    # envFrom 항목에서 컨피그맵에서 읽어 오기
            - configMapRef:           # 환경 변수 정의
              name: [configmap-name]

          volumeMounts:                 # 컨테이너에 마운트할 볼륨 설정
            - name: config              # 마운트할 볼륨 이름
              mountPath: "/app/config"  # 볼륨이 마운트될 경로
              readOnly: true            # 읽기 전용 설정

      volumes:                          # 볼륨 정의 / 볼륨은 파드 수준에서 정의 된다.
        - name: config                  # 볼륨 이름
          configMap:                    # 볼륨의 원본은 컨피그맵
            name: [configmap-name]      # 내용을 읽어올 컨피그맵 이름